apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-web
  description: Backstage Frontend
  annotations:
    argocd/app-name: backstage-prd
    backstage.io/kubernetes-id: backstage
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: devxp-tech/backstage
    grafana/tag-selector: "Kubernetes"
    kubecost.com/deployment-name: "backstage"
    prometheus.io/rule: 'sum by (backstage)(changes(kube_pod_status_ready{condition="true"}[5m]))'
    prometheus.io/alert: all
    sonarqube.org/project-key: backstage
    snyk.io/org-name: devxp-tech
    snyk.io/project-ids: c3c91d87-e14d-40cd-85c6-141e543350ab
  tags:
    - web
    - frontend
    - backstage
  links:
    - url: https://backstage.devxp-tech.io
      title: Backstage
      icon: cloud
spec:
  type: service
  lifecycle: production
  owner: group:sre-team
  system: backstage
  #dependsOn: ['component:bob-cache', 'component:bob-db', 'component:bob-queue']
  apiConsumedBy: ["system:backstage"]
  dependsOn: ["resource:backstage-db", "resource:backstage-bucket"]
  providesApis:
    - backstage
