apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devxp
  description: The acme-corp organization
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: DevXP Labs
    email: info@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [ops]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: teams
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./dev.yaml  
    - ./ops.yaml
    - ./dba.yaml
